name: Scenario files validation

on:
  push:
    paths:
      - "*"

jobs:
  validate-scenario-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate scenario files
        run:  node index.js
        with:
          path_to_files: "scenario"
          api_users: "nsec,system"
